[cockroachdb_cluster]
node1 ansible_host=192.168.1.160 ansible_ssh_private_key_file=~/.ssh/id_rsa
node2 ansible_host=192.168.1.161  ansible_ssh_private_key_file=~/.ssh/id_rsa
node3 ansible_host=192.168.1.162  ansible_ssh_private_key_file=~/.ssh/id_rsa